title: Be an outstanding software engineer
author: Lufei
email: lufei0724@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Everything to be an outstanding software engineer including development, system design, architecture and etc.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
